# Generated by Django 4.0.4 on 2022-10-06 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_date_created_alter_post_date_last_edited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='commentreply',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
