# Generated by Django 4.0.4 on 2022-10-16 15:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0006_alter_post_dislikes_alter_post_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentreply',
            options={'ordering': ['created_at', 'user']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AlterField(
            model_name='post',
            name='dislikers',
            field=models.ManyToManyField(blank=True, null=True, related_name='dislikers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='likers',
            field=models.ManyToManyField(blank=True, null=True, related_name='likers', to=settings.AUTH_USER_MODEL),
        ),
    ]
