# Generated by Django 4.0.4 on 2022-10-16 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0007_alter_commentreply_options_remove_post_dislikes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dislikers',
            field=models.ManyToManyField(blank=True, related_name='dislikers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='likers',
            field=models.ManyToManyField(blank=True, related_name='likers', to=settings.AUTH_USER_MODEL),
        ),
    ]
