# Generated by Django 4.0.4 on 2022-10-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_customuser_is_subscribed_customuser_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, unique=True, verbose_name='A valid email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.TextField(blank=True, max_length=30, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.TextField(blank=True, max_length=30, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Password'),
        ),
    ]
