# Generated by Django 4.0.4 on 2022-10-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='avatar',
            field=models.ImageField(blank=True, default='defaults/avatar.jpg', null=True, upload_to='groups/avatars'),
        ),
        migrations.AlterField(
            model_name='group',
            name='cover',
            field=models.ImageField(blank=True, default='defaults/cover.jpg', null=True, upload_to='groups/covers'),
        ),
    ]
